version: "3.3"
services:
  examples-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
